# Generated by Django 3.1.4 on 2021-02-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20210205_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companytype',
            name='company_type',
            field=models.CharField(max_length=30),
        ),
    ]
