# Generated by Django 3.1.4 on 2021-02-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_auto_20210205_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayyear',
            name='ay_year',
            field=models.CharField(max_length=7),
        ),
    ]
